import type { Metadata } from "next";
import LocalizedServicePage from "@/components/seo/LocalizedServicePage";

export const metadata: Metadata = {
    title: "Pas Foto 4×6 cm, Standar Paspor dan SIM | SS Foto",
    description: "Pas foto 4×6 di SS Foto — standar Imigrasi RI, SIM, dan visa. Background putih solid, file digital untuk M-Paspor tersedia. Langsung jadi.",
    alternates: { canonical: "https://www.ssfoto.co.id/pas-foto-4x6" }
};

export default function Page() {
    return (
        <LocalizedServicePage
            serviceName="SS Foto"
            serviceSlug="pas-foto-4x6"
            headline={"Pas Foto Ukuran 4×6 cm"}
            subheadline={"Ukuran 4×6 cm adalah standar untuk dokumen resmi dengan persyaratan foto paling ketat — paspor, SIM, dan beberapa jenis visa. Berbeda dari ukuran lain yang relatif fleksibel, foto 4×6 untuk paspor dan SIM diperiksa secara ketat oleh petugas — bahkan oleh sistem digital seperti aplikasi M-Paspor.\n\nDi SS Foto, kami mencetak pas foto 4×6 sesuai standar Direktorat Jenderal Imigrasi dan Korlantas Polri — termasuk file digital siap upload M-Paspor."}
            heroImage="/images/products/kertas-cetak-pas-foto-profesional.png"
            benefits={[{ icon: "zap", text: "Proses Cepat" }, { icon: "star", text: "Kualitas Lab" }]}
            contentSections={[
{ title: "Ukuran Pas Foto 4×6 — Spesifikasi Teknis", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ukuran 4×6 mengacu pada: <strong>4 cm lebar × 6 cm tinggi</strong>. Detail teknisnya:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Milimeter:</strong> 40 × 60 mm</li><li><strong>Piksel (300 DPI):</strong> ± 472 × 709 piksel</li><li><strong>Inch:</strong> ± 1,57 × 2,36 inch</li>\n</ul>\n<p>Perbandingan dengan ukuran lain:</p>\n<p>| Ukuran | Dimensi | Dokumen Utama |\n|--------|---------|---------------|\n| <a href=\"/pas-foto-2x3\" class=\"text-[#ea2423] font-semibold hover:underline\">2×3</a> | 2 × 3 cm | KTP, kartu pelajar |\n| 3×4 | 3 × 4 cm | Ijazah, CPNS, lamaran |\n| <strong>4×6</strong> | <strong>4 × 6 cm</strong> | <strong>Paspor, SIM, visa tertentu</strong> |\n</p>\n</div>" }} /> },
{ title: "Tren Pembuatan Paspor di Indonesia", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Indonesia adalah salah satu negara dengan pertumbuhan pemegang paspor tercepat di Asia Tenggara. Kebutuhan pas foto 4×6 ikut meningkat signifikan karena beberapa faktor:</p>\n<p><strong>Boom wisata umroh dan haji:</strong> Jutaan jamaah Indonesia membutuhkan paspor baru setiap tahun — dan pas foto 4×6 adalah salah satu dokumen wajibnya.</p>\n<p><strong>Wisata luar negeri semakin terjangkau:</strong> Meningkatnya penerbangan internasional mendorong lebih banyak warga Indonesia membuat paspor pertama mereka.</p>\n<p><strong>Program kerja luar negeri (PMI):</strong> Pekerja Migran Indonesia yang berangkat ke luar negeri membutuhkan paspor untuk proses keberangkatan.</p>\n<p><strong>Migrasi ke e-Paspor:</strong> Mendorong banyak orang memperbarui paspor lama sekaligus upgrade ke format elektronik.</p>\n<p><strong>Implikasi untuk foto:</strong> Sistem Imigrasi semakin digital. Aplikasi M-Paspor memiliki pengecekan otomatis — background tidak solid atau pencahayaan tidak merata bisa langsung ditolak sistem bahkan sebelum diproses petugas.</p>\n<p>Lihat juga: Pas Foto Paspor · Pas Foto Visa\n</p>\n</div>" }} /> },
{ title: "Dokumen yang Membutuhkan Pas Foto 4×6", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Paspor</strong> — background putih solid, standar Direktorat Jenderal Imigrasi RI</li><li><strong>SIM A, B, C</strong> — background biru, standar Korlantas Polri</li><li><strong>Visa tertentu</strong> — beberapa negara meminta ukuran mendekati 4×6 cm</li><li><strong>Kartu pegawai dan ID korporat</strong> — beberapa perusahaan besar menggunakan standar 4×6</li><li><strong>Perpanjangan paspor</strong> — dokumen pendukung selain paspor lama</li>\n</ul>\n</div>" }} /> },
{ title: "Standar Pas Foto 4×6 untuk Paspor (Imigrasi RI)", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Persyaratan foto paspor Indonesia yang berlaku saat ini:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Ukuran:</strong> 4 × 6 cm untuk cetak fisik</li><li><strong>Background:</strong> Putih polos — tidak boleh ada gradasi, bayangan, atau warna abu-abu</li><li><strong>Wajah:</strong> Tampak depan, kepala tegak, simetris</li><li><strong>Proporsi wajah:</strong> Mengisi 70–80% frame foto</li><li><strong>Jarak dagu ke ujung kepala:</strong> sekitar 2,5–3,5 cm</li><li><strong>Ekspresi:</strong> Netral, mulut tertutup</li><li><strong>Mata:</strong> Terbuka lebar, tidak tertutup kacamata</li><li><strong>Kacamata:</strong> Tidak diperbolehkan — standar Imigrasi RI melarang kacamata</li><li><strong>Penutup kepala:</strong> Tidak diperbolehkan, kecuali alasan agama (hijab diperbolehkan)</li><li><strong>Pakaian:</strong> Tidak berwarna putih — agar kontras dengan background</li><li><strong>Foto harus terbaru:</strong> Dalam 6 bulan terakhir</li><li><strong>File digital M-Paspor:</strong> Maksimal 300 KB, format JPG</li>\n</ul>\n</div>" }} /> },
{ title: "Standar Pas Foto 4×6 untuk SIM (Korlantas Polri)", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Ukuran:</strong> 4 × 6 cm</li><li><strong>Background:</strong> Biru untuk SIM A, B1, B2, C, D</li><li><strong>Pakaian:</strong> Formal — kemeja atau atasan formal</li><li><strong>Ekspresi:</strong> Natural dan serius</li><li><strong>Tidak memakai kacamata</strong> untuk SIM terbaru</li>\n</ul>\n</div>" }} /> },
{ title: "Kenapa Pas Foto Paspor Sering Ditolak?", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ini penyebab paling umum foto paspor ditolak di kantor Imigrasi atau portal M-Paspor:</p>\n<p>1. <strong>Background tidak benar-benar putih</strong> — ada bayangan di background atau warna terlihat abu-abu\n2. <strong>Kacamata masih dipakai</strong> — kebijakan Imigrasi RI melarang kacamata sejak beberapa tahun terakhir\n3. <strong>Proporsi wajah salah</strong> — kepala terlalu kecil atau terlalu besar dalam frame\n4. <strong>File digital tidak sesuai</strong> — ukuran file terlalu besar untuk upload M-Paspor\n5. <strong>Foto sudah lama</strong> — lebih dari 6 bulan sejak pengambilan</p>\n<p>SS Foto mengikuti standar terbaru Ditjen Imigrasi untuk memastikan foto langsung diterima.\n</p>\n</div>" }} /> }
            ]}
            pricing={undefined}
            faq={[{"q":"Apakah foto 4×6 di SS Foto bisa langsung untuk upload M-Paspor?","a":"Ya. SS Foto menyiapkan file digital JPG dengan format dan ukuran yang sesuai untuk portal M-Paspor dari Ditjen Imigrasi — termasuk batasan ukuran file 300 KB."},{"q":"Apakah boleh memakai kacamata untuk foto paspor 4×6?","a":"Tidak. Standar Imigrasi RI saat ini melarang kacamata di foto paspor. Begitu juga untuk SIM terbaru. Lepas kacamata sebelum sesi foto."},{"q":"Apakah bisa pakai hijab untuk foto paspor 4×6?","a":"Bisa. Hijab diperbolehkan selama wajah — dari dahi hingga dagu — terlihat jelas dan tidak ada bayangan yang menutupi wajah."},{"q":"Berapa lembar foto 4×6 yang dibutuhkan untuk paspor?","a":"Kantor Imigrasi biasanya meminta 2 lembar. SS Foto menyarankan cetak 4–6 lembar untuk cadangan dan keperluan dokumen lain seperti visa atau asuransi perjalanan."},{"q":"Berapa lama proses foto 4×6 di SS Foto?","a":"Rata-rata 10–15 menit dari sesi foto hingga cetak dan file digital siap."}]}
        />
    );
}
