import type { Metadata } from "next";
import LocalizedServicePage from "@/components/seo/LocalizedServicePage";

export const metadata: Metadata = {
    title: "Ukuran Pas Foto 2x3, 3x4, 4x6 — Panduan Lengkap untuk Semua Dokumen",
    description: "Panduan ukuran pas foto standar Indonesia — 2×3, 3×4, 4×6, dan standar internasional. Background, ketentuan per dokumen, dan cara cetak yang benar.",
    alternates: { canonical: "https://www.ssfoto.co.id/ukuran-pas-foto" }
};

export default function Page() {
    return (
        <LocalizedServicePage
            serviceName="SS Foto"
            serviceSlug="ukuran-pas-foto"
            headline={"Ukuran Pas Foto Standar Indonesia — Panduan Lengkap"}
            subheadline={"Ukuran pas foto bukan sesuatu yang bisa ditebak-tebak. Ukuran yang salah meskipun hanya sedikit bisa menyebabkan berkas ditolak — mulai dari penolakan di portal SSCASN untuk CPNS, hingga penolakan di kantor Imigrasi saat pembuatan paspor.\n\nPanduan ini menjelaskan semua ukuran pas foto standar yang berlaku di Indonesia beserta ketentuan masing-masing dokumen."}
            heroImage="/images/products/kertas-cetak-pas-foto-profesional.png"
            benefits={[{ icon: "zap", text: "Proses Cepat" }, { icon: "star", text: "Kualitas Lab" }]}
            contentSections={[
{ title: "Tabel Ukuran Pas Foto Standar Indonesia", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>| Ukuran | Dimensi (cm) | Dimensi (mm) | Dokumen Utama |\n|--------|-------------|-------------|----------------|\n| 2×3 | 2 × 3 cm | 20 × 30 mm | KTP, kartu pelajar, administrasi kelurahan |\n| 3×4 | 3 × 4 cm | 30 × 40 mm | Ijazah, CPNS, lamaran kerja, SKCK, beasiswa |\n| 4×6 | 4 × 6 cm | 40 × 60 mm | Paspor, SIM, visa tertentu |\n</p>\n</div>" }} /> },
{ title: "Ukuran 2×3 — Untuk Apa?", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ukuran 2×3 adalah ukuran pas foto terkecil yang umum digunakan. Detail:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Dimensi:</strong> 2 cm × 3 cm (20 mm × 30 mm)</li><li><strong>Dokumen:</strong> KTP, Kartu Keluarga, kartu pelajar, formulir kelurahan dan kecamatan</li><li><strong>Background:</strong> Merah untuk sebagian besar dokumen pemerintah; biru untuk beberapa dokumen lain</li><li><strong>Catatan:</strong> Meski kecil, standar kualitasnya tetap sama — background solid, pencahayaan merata, wajah tampak jelas</li>\n</ul>\n<p>→ Panduan lengkap pas foto 2×3\n</p>\n</div>" }} /> },
{ title: "Ukuran 3×4 — Paling Universal", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ukuran 3×4 adalah yang paling banyak digunakan dalam sistem administrasi Indonesia. Hampir semua dokumen formal menggunakan ukuran ini.</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Dimensi:</strong> 3 cm × 4 cm (30 mm × 40 mm)</li><li><strong>Dokumen:</strong> Ijazah SD–S3, CPNS/BKN, SKCK, lamaran kerja, beasiswa, pendaftaran kampus</li><li><strong>Background:</strong> Merah (lahir ganjil untuk CPNS), Biru (lahir genap untuk CPNS), Merah untuk ijazah nasional</li><li><strong>Catatan:</strong> Background merah/biru untuk CPNS ditentukan oleh tahun kelahiran pelamar</li>\n</ul>\n<p>→ Panduan lengkap pas foto 3×4\n</p>\n</div>" }} /> },
{ title: "Ukuran 4×6 — Untuk Paspor dan SIM", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ukuran 4×6 adalah standar untuk dokumen resmi yang memerlukan verifikasi identitas paling ketat.</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Dimensi:</strong> 4 cm × 6 cm (40 mm × 60 mm)</li><li><strong>Dokumen:</strong> Paspor Indonesia, SIM A/B/C, visa tertentu, ID korporat</li><li><strong>Background:</strong> Putih solid (paspor), Biru (SIM)</li><li><strong>Catatan khusus paspor:</strong> Wajah mengisi 70–80% frame, tanpa kacamata, pakaian tidak berwarna putih</li>\n</ul>\n<p>→ Panduan lengkap pas foto 4×6\n</p>\n</div>" }} /> },
{ title: "Ukuran Pas Foto Internasional", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Beberapa dokumen internasional menggunakan ukuran berbeda dari standar Indonesia:</p>\n<p>| Negara / Dokumen | Ukuran | Background |\n|-----------------|--------|------------|\n| Visa Schengen (Eropa) | 3,5 × 4,5 cm | Putih |\n| Visa Amerika Serikat | 5 × 5 cm | Putih |\n| Visa Australia | 3,5 × 4,5 cm | Putih/terang |\n| Visa Jepang | 4,5 × 4,5 cm | Putih |\n| Visa Arab Saudi (Umroh) | 4 × 6 cm | Putih |</p>\n<p>→ Panduan lengkap pas foto visa\n</p>\n</div>" }} /> },
{ title: "Standar Background Pas Foto per Dokumen", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Background bukan hanya estetika — ini adalah persyaratan teknis yang kalau salah bisa menyebabkan penolakan:</p>\n<p>| Dokumen | Background Wajib | Catatan |\n|---------|-----------------|---------|\n| Paspor Indonesia | <strong>Putih solid</strong> | Wajib, tidak boleh abu-abu |\n| CPNS (lahir ganjil) | <strong>Merah</strong> | Ketentuan BKN |\n| CPNS (lahir genap) | <strong>Biru</strong> | Ketentuan BKN |\n| SIM | <strong>Biru</strong> | Standar Korlantas Polri |\n| Ijazah SD–S3 | <strong>Merah</strong> | Standar Kemendikbud |\n| Visa | <strong>Putih</strong> | Sesuai ketentuan kedutaan |\n| KTP | <strong>Merah/Biru</strong> | Ketentuan Dukcapil setempat |\n</p>\n</div>" }} /> },
{ title: "Standar Teknis Pas Foto yang Sering Diabaikan", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Selain ukuran dan background, ada beberapa ketentuan teknis yang sering diabaikan:</p>\n<p><strong>Proporsi wajah dalam frame:</strong>\n- Wajah harus mengisi 70–80% area foto\n- Terlalu kecil atau terlalu besar bisa menyebabkan penolakan — terutama untuk paspor dan visa</p>\n<p><strong>Kacamata:</strong>\n- Paspor dan visa: <strong>tidak boleh memakai kacamata</strong> (kebijakan terbaru)\n- SIM: umumnya juga tidak boleh memakai kacamata</p>\n<p><strong>Ekspresi:</strong>\n- Netral, mulut tertutup\n- Tidak boleh senyum terlalu lebar\n- Mata terbuka dan menatap kamera lurus</p>\n<p><strong>Pencahayaan:</strong>\n- Background harus benar-benar solid — tidak ada bayangan atau gradasi\n- Tidak ada bayangan di wajah atau leher\n</p>\n</div>" }} /> },
{ title: "Kenapa Pas Foto dari HP Sering Tidak Diterima?", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Banyak orang mencoba foto sendiri di rumah menggunakan HP. Masalah yang sering muncul:</p>\n<p>1. <strong>Background tidak solid</strong> — pencahayaan HP tidak bisa menghasilkan background yang benar-benar solid seperti studio\n2. <strong>Proporsi wajah salah</strong> — sulit mengukur apakah wajah mengisi 70–80% frame dengan benar\n3. <strong>Ukuran file digital tidak sesuai</strong> — portal online memiliki batas maksimal ukuran file\n4. <strong>Hasil cetak buram</strong> — foto dikompres saat dikirim via WhatsApp sebelum dicetak</p>\n<p>Di SS Foto, semua masalah ini dieliminasi dengan studio lighting profesional dan sistem produksi yang sudah dioptimasi untuk semua jenis dokumen.\n</p>\n</div>" }} /> },
{ title: "Cetak Pas Foto dengan Ukuran yang Tepat di SS Foto", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>SS Foto menyediakan layanan pas foto untuk semua ukuran standar Indonesia dan internasional:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><a href=\"/pas-foto-2x3\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto 2×3</a> — KTP dan dokumen dasar</li><li><a href=\"/pas-foto-3x4\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto 3×4</a> — ijazah, CPNS, lamaran kerja</li><li><a href=\"/pas-foto-4x6\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto 4×6</a> — paspor dan SIM</li><li><a href=\"/pas-foto\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto CPNS</a> — standar BKN, file digital SSCASN</li><li><a href=\"/pas-foto\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto Paspor</a> — standar Imigrasi RI, file digital M-Paspor</li><li><a href=\"/pas-foto\" class=\"text-[#ea2423] font-semibold hover:underline\">Pas Foto Visa</a> — sesuai ketentuan kedutaan masing-masing negara</li>\n</ul>\n<p>Tersedia di <a href=\"/lokasi\" class=\"text-[#ea2423] font-semibold hover:underline\">5 cabang SS Foto</a> di Jakarta Timur, Bekasi, Bogor, dan Jakarta Selatan.\n</p>\n</div>" }} /> }
            ]}
            pricing={undefined}
            faq={[{"q":"Ukuran pas foto apa yang paling umum digunakan di Indonesia?","a":"Ukuran 3×4 adalah yang paling universal — digunakan untuk ijazah, CPNS, lamaran kerja, SKCK, dan beasiswa. Hampir semua formulir resmi Indonesia menggunakan ukuran ini."},{"q":"Apa perbedaan ukuran 2×3 dan 3×4?","a":"Ukuran 2×3 (2cm×3cm) lebih kecil dari 3×4 (3cm×4cm). Keduanya digunakan untuk dokumen yang berbeda — 2×3 untuk KTP dan kartu pelajar, 3×4 untuk ijazah dan dokumen formal yang lebih penting."},{"q":"Berapa ukuran pas foto untuk paspor Indonesia?","a":"Paspor Indonesia menggunakan ukuran 4×6 cm dengan background putih solid. Detail lengkap di halaman Pas Foto Paspor."},{"q":"Apakah ukuran foto bisa sedikit berbeda dari standar?","a":"Tidak disarankan. Instansi pemerintah dan portal digital seringkali menolak foto yang tidak sesuai ukuran standar — bahkan selisih 1–2 mm pun bisa bermasalah."},{"q":"Dimana bisa cetak pas foto dengan semua ukuran standar?","a":"SS Foto menyediakan semua ukuran standar Indonesia dan internasional di semua cabang — Jakarta Timur, Bekasi, Bogor, dan Jakarta Selatan. Lihat [semua cabang](/lokasi)."}]}
        />
    );
}
