import type { Metadata } from "next";
import LocalizedServicePage from "@/components/seo/LocalizedServicePage";

export const metadata: Metadata = {
    title: "Pas Foto 3×4 cm, Standar Ijazah, CPNS & Lamaran Kerja | SS Foto",
    description: "Pas foto 3×4 di SS Foto — standar ijazah, lamaran kerja, CPNS, dan dokumen resmi. Proses cepat, hasil profesional, file digital tersedia.",
    alternates: { canonical: "https://www.ssfoto.co.id/pas-foto-3x4" }
};

export default function Page() {
    return (
        <LocalizedServicePage
            serviceName="SS Foto"
            serviceSlug="pas-foto-3x4"
            headline={"Pas Foto Ukuran 3×4 cm"}
            subheadline={"Ukuran 3×4 cm adalah ukuran pas foto yang paling banyak diminta di Indonesia. Dari ijazah sekolah, [lamaran kerja](/pas-foto), pendaftaran CPNS, SKCK, hingga berbagai formulir pemerintah — hampir semua dokumen resmi menggunakan ukuran ini.\n\nDi SS Foto, kami mencetak pas foto 3×4 dengan standar yang ketat: ukuran presisi, pencahayaan studio merata, dan background solid tanpa gradasi. Hasilnya langsung diterima instansi."}
            heroImage="/images/products/kertas-cetak-pas-foto-profesional.png"
            benefits={[{ icon: "zap", text: "Proses Cepat" }, { icon: "star", text: "Kualitas Lab" }]}
            contentSections={[
{ title: "Ukuran Pas Foto 3×4 — Detail Spesifikasi", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ukuran 3×4 mengacu pada dimensi cetak fisik: <strong>3 cm lebar × 4 cm tinggi</strong>. Detail teknisnya:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Milimeter:</strong> 30 × 40 mm</li><li><strong>Piksel (300 DPI):</strong> ± 354 × 472 piksel</li><li><strong>Inch:</strong> ± 1,18 × 1,57 inch</li>\n</ul>\n<p>Dibanding ukuran lain:</p>\n<p>| Ukuran | Lebar × Tinggi | Paling Cocok Untuk |\n|--------|----------------|-------------------|\n| 2×3 | 2 × 3 cm | KTP, kartu pelajar |\n| <strong>3×4</strong> | <strong>3 × 4 cm</strong> | <strong>Ijazah, CPNS, lamaran kerja — universal</strong> |\n| 4×6 | 4 × 6 cm | Paspor, SIM |</p>\n<p>Standarisasi 3×4 terbentuk karena ukuran ini efisien di formulir cetak sekaligus cukup besar untuk menampilkan wajah dengan jelas — titik keseimbangan yang tidak dimiliki ukuran lain.\n</p>\n</div>" }} /> },
{ title: "Dokumen yang Membutuhkan Pas Foto 3×4", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Hampir semua dokumen formal di Indonesia menggunakan ukuran 3×4:</p>\n<ul class=\"list-disc pl-5 space-y-2\">\n<li><strong>Ijazah</strong> — SD, SMP, SMA, SMK, Diploma, S1, S2, S3</li><li><strong>Lamaran kerja</strong> — CV fisik dan berkas administrasi (lihat: Pas Foto Lamaran Kerja)</li><li><strong>Pendaftaran CPNS</strong> — salah satu dokumen wajib sesuai ketentuan BKN (lihat: Pas Foto CPNS)</li><li><strong>SKCK</strong> — Surat Keterangan Catatan Kepolisian dari Polri</li><li><strong>Beasiswa</strong> — LPDP, beasiswa pemerintah, dan beasiswa swasta</li><li><strong>Pendaftaran sekolah dan kampus</strong> — PPDB, SNBP, UTBK, jalur mandiri</li><li><strong>Kartu anggota profesi</strong> — IDI, PGRI, dan berbagai organisasi profesi lainnya</li><li><strong>Formulir administrasi pemerintah</strong> — berbagai keperluan di kantor dinas dan kelurahan</li>\n</ul>\n</div>" }} /> },
{ title: "Kenapa 3×4 Jadi Ukuran Paling Universal?", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Ada alasan historis dan praktis mengapa 3×4 mendominasi sistem administrasi Indonesia:</p>\n<p><strong>Efisiensi formulir cetak:</strong> Ukuran 3×4 muat secara proporsional di kolom foto yang tersedia di sebagian besar formulir standar Indonesia — tidak terlalu kecil sehingga identitas sulit diverifikasi, tidak terlalu besar sehingga menghabiskan ruang formulir.</p>\n<p><strong>Standardisasi sistem nasional:</strong> Sistem administrasi Indonesia — dari Kemendikbud untuk ijazah nasional, BKN untuk CPNS, hingga Polri untuk SKCK — semuanya mengadopsi 3×4 sebagai standar utama. Artinya ukuran ini akan tetap relevan dalam jangka panjang.</p>\n<p><strong>Detail wajah cukup untuk verifikasi:</strong> Berbeda dengan 2×3 yang detail wajahnya sangat terbatas, foto 3×4 memberikan cukup detail untuk proses verifikasi identitas secara visual maupun digital.\n</p>\n</div>" }} /> },
{ title: "Standar Pas Foto 3×4 yang Diterima Instansi", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Agar pas foto 3×4 diterima, harus memenuhi standar berikut:</p>\n<p><strong>Ukuran dan komposisi:</strong>\n- Tepat 3 × 4 cm — instansi tidak menerima foto yang tidak presisi\n- Wajah mengisi 70–80% frame\n- Tampak depan, posisi kepala tegak</p>\n<p><strong>Background:</strong>\n- <strong>Merah</strong> untuk tahun kelahiran ganjil (CPNS/BKN)\n- <strong>Biru</strong> untuk tahun kelahiran genap (CPNS/BKN)\n- Merah atau biru tergantung ketentuan dokumen lainnya\n- Solid tanpa gradasi atau bayangan</p>\n<p><strong>Kualitas foto:</strong>\n- Pencahayaan merata — tidak ada bayangan di wajah\n- Tidak buram atau pixelated\n- File digital: biasanya 120–300 KB JPG untuk upload portal</p>\n<p><strong>Penampilan:</strong>\n- Ekspresi natural, serius tapi tidak kaku\n- Pakaian formal — kemeja atau jas\n- Tidak memakai topi atau kacamata\n</p>\n</div>" }} /> },
{ title: "Kenapa Pas Foto 3×4 Sering Ditolak?", content: <div dangerouslySetInnerHTML={{ __html: "<div class=\"space-y-4\">\n<p>Meskipun terlihat sederhana, banyak pas foto 3×4 yang ditolak instansi. Alasan paling umum:</p>\n<p>1. <strong>Background tidak solid</strong> — ada gradasi, bayangan, atau warna tidak rata karena foto di tempat pencahayaan buruk\n2. <strong>Ukuran file digital salah</strong> — terlalu besar atau kecil untuk upload di portal SSCASN atau sistem rekrutmen\n3. <strong>Foto buram</strong> — akibat dikompres berkali-kali via WhatsApp sebelum upload\n4. <strong>Background salah warna</strong> — merah/biru tertukar untuk pendaftaran CPNS\n5. <strong>Ukuran cetak tidak presisi</strong> — foto terlalu kecil atau besar dari standar 3×4</p>\n<p>Di SS Foto, semua masalah ini sudah diantisipasi sejak awal. Tim kami memastikan spesifikasi tepat sesuai dokumen yang dibutuhkan.\n</p>\n</div>" }} /> }
            ]}
            pricing={undefined}
            faq={[{"q":"Pas foto 3×4 untuk CPNS, background apa yang benar?","a":"Background merah untuk tahun kelahiran ganjil (1991, 1993, 1995, dst.), biru untuk tahun kelahiran genap (1992, 1994, 1996, dst.). Selalu cek pengumuman resmi instansi yang dilamar karena ketentuan bisa berubah tiap tahun. Panduan lengkap di halaman Pas Foto CPNS."},{"q":"Berapa ukuran file digital 3×4 yang dibutuhkan untuk upload SSCASN?","a":"Biasanya maksimal 200 KB dalam format JPG. SS Foto menyiapkan file dengan ukuran yang tepat — tidak perlu kompres sendiri yang bisa merusak kualitas."},{"q":"Apakah pakaian mempengaruhi hasil foto 3×4?","a":"Ya, sangat. Untuk lamaran kerja dan dokumen formal, kemeja berwarna solid atau jas memberikan kesan profesional yang jauh lebih baik dari kaos. Tim SS Foto bisa menyarankan pakaian yang paling sesuai."},{"q":"Berapa lama proses pas foto 3×4?","a":"Rata-rata 10–15 menit dari sesi foto hingga hasil cetak siap."},{"q":"Apakah bisa minta file digital 3×4 untuk upload online?","a":"Ya. SS Foto menyediakan file JPG dengan resolusi dan ukuran yang sesuai untuk semua portal online — SSCASN, rekrutmen perusahaan, portal beasiswa, dan lainnya."}]}
        />
    );
}
